name: "Go action"
description: "descripcion my tediosa"
author: "Jorge López Rosende"
inputs:
  args:
    description: "Argumentos del ejecutable"
    required: true
outputs:
  function_matrix:
    description: "outputs params to run matrix actions"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}