name: 1 - SISU CI - Java

on:
  pull_request:
    paths:
      - cloud/**
      - code/**
      - db/**
      - .github/workflows/**

  workflow_dispatch:
    inputs:
      from:
        description: Branch, commit or release to run Tests
        default: ""
        required: false

jobs:
  unit-test:
    uses: inditex/lib-sisucommonsgh/.github/workflows/unit-test-java.yml@v2.0.0-java-alpha.6
    with:
      from: ${{ inputs.from }}
    secrets:
      DIST_PLAT_READER_USERNAME: ${{ secrets.DIST_PLAT_READER_USERNAME }}
      DIST_PLAT_READER_TOKEN: ${{ secrets.DIST_PLAT_READER_TOKEN }}
      DT_ENDPOINT: ${{ secrets.DT_ENDPOINT }}
      DT_SECRET: ${{ secrets.DT_SECRET }}
      GH_TOKEN_READER: ${{ secrets.GH_TOKEN_READER }}

  integration-test:
    uses: inditex/lib-sisucommonsgh/.github/workflows/integration-test-java.yml@v2.0.0-java-alpha.6
    with:
      from: ${{ inputs.from }}
    secrets:
      DIST_PLAT_READER_USERNAME: ${{ secrets.DIST_PLAT_READER_USERNAME }}
      DIST_PLAT_READER_TOKEN: ${{ secrets.DIST_PLAT_READER_TOKEN }}
      DT_ENDPOINT: ${{ secrets.DT_ENDPOINT }}
      DT_SECRET: ${{ secrets.DT_SECRET }}
      GH_TOKEN_READER: ${{ secrets.GH_TOKEN_READER }}
