name: Build with Github

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["linux", "darwin", "windows"]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: code/go.mod
          cache-dependency-path: |
            code/go.sum
    
      - name: Run Dagger pipeline
        working-directory: code
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: "0"
        run: go go build -o ../build/sisu-${{ matrix.os }}-${{ matrix.arch }}