name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - name: Run Dagger pipeline
        run: go run -n main.go
