name: Build with Dagger

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: pipelines/go.mod
          cache-dependency-path: |
            pipelines/go.sum

      - id: go-cache-paths
        run: |
          mkdir -p ${{ runner.temp }}/go-build
          mkdir -p ${{ runner.temp }}/go-mod
          echo "go-build=${{ runner.temp }}/go-build" >> $GITHUB_OUTPUT
          echo "go-mod=${{ runner.temp }}/go-mod" >> $GITHUB_OUTPUT

      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('code/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('code/go.sum') }}

      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      
      - name: Run Dagger pipeline
        working-directory: code
        env:
          GO_CACHE: ${{ steps.go-cache-paths.outputs.go-build }}
          GO_MODCACHE: ${{ steps.go-cache-paths.outputs.go-mod }}
        run: dagger run go run ${{ github.workspace }}/pipelines/cd/release