on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to upload files
        required: true
        type: string
        default: ""

permissions: write-all

jobs:
  compile:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - uses: actions/checkout@v3

      - name: Run Dagger pipeline
        run: go run ./ci-cd/build.go --tag ${{ github.ref_name }}

      - name: "Upload files to release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ inputs.tag || github.ref_name }} $(ls ./build/*) --clobber
