on:
  release:
    types:
      - published

permissions: write-all

jobs:
  compile:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: actions/checkout@v3

      - name: Run Dagger pipeline
        run: go run ./ci-cd/build.go

      - name: "Upload files to release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} $(ls ./build/*) --clobber
