
name: Test

on: 
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    outputs:
      function_matrix: "{ \"include\": ${{ steps.action.outputs.function_matrix }} }"

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test action
        id: action
        uses: ./
        with:
          args: deploy --config test/0-azure.yml -e pre -f 1.0.0

      - name: Check outputs 
        run: |
          echo "${{ steps.action.outputs.function_matrix }}"

      - name: Check outputs json 
        run: |
          echo "${{ toJson(steps.action.outputs.function_matrix) }}"

  run-matrix:
    name: Check Matrix
    runs-on: ubuntu-latest
    needs: 
      - test
    
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.test.outputs.function_matrix) }}

    steps: 
      - name: ${{ matrix.name }}
        run: echo "${{ toJson(matrix) }}"
