
name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Test action
        id: action
        uses: ./

      - name: Check outputs 
        run: |
          echo "${{ toJSON(steps.action.outputs) }}"
                