
name: Test

on: 
  push:
  workflow_dispatch:
    inputs:
      env:
        default: dev
        description: environment to select function to deploy

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    outputs:
      function_matrix: ${{ steps.action.outputs.function_matrix }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install binary
        uses: ./
        with: 
          version: "0.0.1"

      - name: Run go-action
        id: action
        run: |
          go-action deploy --config test/0-azure.yml -e ${{ inputs.env }} -f 1.0.0

  run-matrix:
    name: Check Matrix
    runs-on: ubuntu-latest
    needs: 
      - test
    
    strategy:
      fail-fast: false
      matrix: 
        include: ${{ fromJson(needs.test.outputs.function_matrix) }}

    steps: 
      - name: ${{ matrix.name }}
        run: echo "${{ toJson(matrix) }}"
