
name: Test

on: 
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test action
        id: action
        uses: ./

      - name: Check outputs 
        run: |
          echo "${{ toJSON(steps.action.outputs) }}"
                